# Generated by Django 6.0.6 on 2026-07-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeuser',
            name='username',
        ),
    ]
