# Generated by Django 6.0.6 on 2026-07-07 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_coordinator_faculty_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examformrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
