# Generated by Django 6.0.6 on 2026-07-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_examformrecord_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examformrecord',
            name='form_status',
            field=models.CharField(choices=[('Not forwarded by the institution.', 'Not Forwarded by Institution'), ('Forwarded by Institution', 'Forwarded by Institution'), ('Submitted To IPS Academy', 'Submitted To IPS Academy')], default='Not forwarded by the institution.', max_length=50),
        ),
        migrations.AlterField(
            model_name='examformrecord',
            name='form_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('ATKT', 'ATKT')], default='Regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='examformrecord',
            name='payment_status',
            field=models.CharField(choices=[('Payment Closed.', 'Payment Closed'), ('Payment Pending', 'Payment Pending'), ('Payment Successful', 'Payment Successful')], default='Payment Closed.', max_length=50),
        ),
        migrations.AlterField(
            model_name='examformrecord',
            name='session',
            field=models.CharField(choices=[('2026-2027(July-Dec)', '2026-2027(July-Dec)'), ('2025-2026(Jan-June)', '2025-2026(Jan-June)')], default='2026-2027(July-Dec)', max_length=50),
        ),
    ]
