# Generated by Django 6.0.6 on 2026-07-07 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_examformrecord_form_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., CSIT-3A, B4', max_length=50)),
                ('branch', models.CharField(help_text='e.g., CSE, CSIT, AIML', max_length=100)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'All Batches',
            },
        ),
        migrations.CreateModel(
            name='FirstYearBatch',
            fields=[
            ],
            options={
                'verbose_name': '1st Year Batch',
                'verbose_name_plural': '1st Year Batches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.batch',),
        ),
        migrations.CreateModel(
            name='FourthYearBatch',
            fields=[
            ],
            options={
                'verbose_name': '4th Year Batch',
                'verbose_name_plural': '4th Year Batches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.batch',),
        ),
        migrations.CreateModel(
            name='SecondYearBatch',
            fields=[
            ],
            options={
                'verbose_name': '2nd Year Batch',
                'verbose_name_plural': '2nd Year Batches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.batch',),
        ),
        migrations.CreateModel(
            name='ThirdYearBatch',
            fields=[
            ],
            options={
                'verbose_name': '3rd Year Batch',
                'verbose_name_plural': '3rd Year Batches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.batch',),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='portal.batch'),
        ),
    ]
