# Generated by Django 6.0.6 on 2026-07-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_batch_firstyearbatch_fourthyearbatch_secondyearbatch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={'verbose_name': 'Coordinator', 'verbose_name_plural': '1. Coordinators'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': '2. Faculties'},
        ),
        migrations.AlterModelOptions(
            name='firstyearbatch',
            options={'verbose_name': '1st Year Branches', 'verbose_name_plural': '3. B.Tech (1st Year)'},
        ),
        migrations.AlterModelOptions(
            name='fourthyearbatch',
            options={'verbose_name': '4th Year Branches', 'verbose_name_plural': '6. B.Tech (4th Year)'},
        ),
        migrations.AlterModelOptions(
            name='secondyearbatch',
            options={'verbose_name': '2nd Year Branches', 'verbose_name_plural': '4. B.Tech (2nd Year)'},
        ),
        migrations.AlterModelOptions(
            name='thirdyearbatch',
            options={'verbose_name': '3rd Year Branches', 'verbose_name_plural': '5. B.Tech (3rd Year)'},
        ),
        migrations.RemoveField(
            model_name='batch',
            name='name',
        ),
    ]
