# Generated by Django 6.0.6 on 2026-07-07 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_coordinator_options_alter_faculty_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., CSE, CSIT, AIML', max_length=100)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'All Branches',
            },
        ),
        migrations.DeleteModel(
            name='FirstYearBatch',
        ),
        migrations.DeleteModel(
            name='FourthYearBatch',
        ),
        migrations.DeleteModel(
            name='SecondYearBatch',
        ),
        migrations.DeleteModel(
            name='ThirdYearBatch',
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.RemoveField(
            model_name='batch',
            name='year',
        ),
        migrations.AddField(
            model_name='batch',
            name='name',
            field=models.CharField(default='Section A', help_text='e.g., Section A, CSIT-1', max_length=50),
        ),
        migrations.CreateModel(
            name='FirstYearBranch',
            fields=[
            ],
            options={
                'verbose_name': '1st Year Branches',
                'verbose_name_plural': '3. B.Tech (1st Year)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.branch',),
        ),
        migrations.CreateModel(
            name='FourthYearBranch',
            fields=[
            ],
            options={
                'verbose_name': '4th Year Branches',
                'verbose_name_plural': '6. B.Tech (4th Year)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.branch',),
        ),
        migrations.CreateModel(
            name='SecondYearBranch',
            fields=[
            ],
            options={
                'verbose_name': '2nd Year Branches',
                'verbose_name_plural': '4. B.Tech (2nd Year)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.branch',),
        ),
        migrations.CreateModel(
            name='ThirdYearBranch',
            fields=[
            ],
            options={
                'verbose_name': '3rd Year Branches',
                'verbose_name_plural': '5. B.Tech (3rd Year)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.branch',),
        ),
        migrations.AlterField(
            model_name='batch',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='portal.branch'),
        ),
    ]
