# Generated by Django 6.0.6 on 2026-07-07 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_branch_delete_firstyearbatch_delete_fourthyearbatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(default='Section A', max_length=50),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='portal.branch')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='MSTMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mst_1_marks', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('mst_2_marks', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='mst_marks', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mst_marks', to='portal.subject')),
            ],
            options={
                'verbose_name': 'MST Mark',
                'verbose_name_plural': 'MST Marks',
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='SubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='portal.batch')),
                ('faculty', models.ForeignKey(limit_choices_to={'user_type': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='portal.subject')),
            ],
            options={
                'verbose_name': 'Subject Allocation',
                'verbose_name_plural': 'Subject Allocations',
                'unique_together': {('faculty', 'batch', 'subject')},
            },
        ),
    ]
