# Generated by Django 6.0.6 on 2026-07-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
    ]
