# Generated by Django 6.0.6 on 2026-07-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_leaveapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
