# Generated by Django 6.0.6 on 2026-07-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_collegeuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeuser',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collegeuser',
            name='email_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collegeuser',
            name='public_directory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collegeuser',
            name='share_gpa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collegeuser',
            name='sms_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collegeuser',
            name='two_factor_auth',
            field=models.BooleanField(default=False),
        ),
    ]
